# Generated by Django 5.0.2 on 2024-03-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_details',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=50),
        ),
    ]
