# Generated by Django 5.0.2 on 2024-03-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_accessories_id_remove_account_details_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='brandID',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='categoryID',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='order_items',
            old_name='orderID',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_items',
            old_name='productID',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='brandID',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categoryID',
            new_name='category',
        ),
    ]
