# Generated by Django 5.0.2 on 2024-03-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_rename_brandid_accessories_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='product',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Account_details',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
